(()=>{"use strict";
const GH={owner:"Agent75-ai",repo:"atlas-canon-data",branch:"main"};
const FILES={meta:"meta.json",canon:"canon.json",decisiones:"decisiones.json",pendientes:"pendientes.json",auditoria:"auditoria.json",integracion:"integracion.json",concordancia:"concordancia.json",civilizaciones:"civilizaciones.json",libro1:"libro1.json",conversaciones:"conversaciones.json",media:"media.json"};
const OPTIONAL=new Set(["conversaciones","media"]);
const SESSION_KEY="atlas-gh-token-session",LOCAL_KEY="atlas-gh-token-local",THEME_KEY="atlas-theme";
let token=sessionStorage.getItem(SESSION_KEY)||localStorage.getItem(LOCAL_KEY)||"";
let data=null,shas={},active="escritorio",decisionTab="decisiones",activeDecisionId="",canonSection="Premisa y mundo",libraryTab="imagenes",techCollection="canon",editing=null,dirty=new Set(),saving=new Set(),saveTimers={},conflictKey="",mediaCache=new Map(),selectedMapId="";
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const clone=v=>JSON.parse(JSON.stringify(v));
const api=path=>`https://api.github.com/repos/${GH.owner}/${GH.repo}/contents/${path}`;
const labels={canon:"Canon",decisiones:"Decisiones",pendientes:"Pendientes",auditoria:"Auditoría",integracion:"Fuentes",concordancia:"Concordancia",civilizaciones:"Civilizaciones",libro1:"Libro I",conversaciones:"Conversaciones",media:"Imágenes"};
function decodeGitHubBase64(s){const bytes=Uint8Array.from(atob(s.replace(/\n/g,"")),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encodeGitHubBase64(s){const bytes=new TextEncoder().encode(s);let bin="";for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin)}
function toast(m){const n=document.createElement("div");n.className="toast";n.textContent=m;$("toasts").append(n);setTimeout(()=>n.remove(),3000)}
function syncStatus(kind,text){$("syncDot").className=`dot ${kind||""}`;$("syncText").textContent=text}
async function gh(method,url,body){let last;for(let attempt=0;attempt<3;attempt++){try{const headers={Authorization:`token ${token}`,...(body?{"Content-Type":"application/json"}:{})};const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined,cache:"no-store",mode:"cors"});if(!r.ok){const e=await r.json().catch(()=>({message:r.statusText}));const err=new Error(e.message||`GitHub ${r.status}`);err.status=r.status;throw err}return r.json()}catch(e){last=e;if(e.status)throw e;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,650*(attempt+1)))}}throw new Error(`No se pudo conectar con GitHub: ${last?.message||"error de red"}`)}
async function loadFile(key){try{const r=await gh("GET",`${api(FILES[key])}?ref=${GH.branch}`),text=decodeGitHubBase64(r.content),obj=JSON.parse(text);shas[key]=r.sha;return obj}catch(e){if(OPTIONAL.has(key)&&e.status===404){shas[key]=null;return []}throw e}}
async function pull(){if(!token)return openConnect();syncStatus("","Cargando desde GitHub…");try{const map={};for(const key of Object.keys(FILES)){syncStatus("",`Cargando ${labels[key]||key}…`);map[key]=await loadFile(key)}data={...map.meta,collections:{},media:Array.isArray(map.media)?map.media:[]};for(const key of Object.keys(FILES))if(!["meta","media"].includes(key))data.collections[key]=Array.isArray(map[key])?map[key]:[];dirty.clear();mediaCache.clear();syncStatus("ok","Sincronizado");render();toast("Atlas cargado desde GitHub")}catch(e){syncStatus("bad","Error de conexión");if(e.status===401||e.status===403){token="";sessionStorage.removeItem(SESSION_KEY);localStorage.removeItem(LOCAL_KEY);openConnect(`GitHub rechazó el token: ${e.message}`)}else openConnect(e.message)}}
function sourceFor(key){return key==="media"?data.media:data.collections[key]}
async function saveCollection(key,force=false){if(!data||!token||saving.has(key)||(!dirty.has(key)&&!force))return;saving.add(key);syncStatus("",`Guardando ${labels[key]||key}…`);try{let useSha=shas[key];if(force&&useSha){const latest=await gh("GET",`${api(FILES[key])}?ref=${GH.branch}`);useSha=latest.sha}const body={message:`Atlas del Canon: ${labels[key]||key} · ${new Date().toLocaleString("es-AR")}`,content:encodeGitHubBase64(JSON.stringify(sourceFor(key),null,2)),branch:GH.branch};if(useSha)body.sha=useSha;const r=await gh("PUT",api(FILES[key]),body);shas[key]=r.content.sha;dirty.delete(key);syncStatus("ok",dirty.size?`${dirty.size} sección(es) pendientes`:"Sincronizado");if(conflictKey===key){conflictKey="";$("conflictBg").hidden=true}toast(`${labels[key]||key} guardado en GitHub`)}catch(e){if(e.status===409||e.status===422){conflictKey=key;syncStatus("bad","Conflicto de versión");$("conflictBg").hidden=false}else{syncStatus("bad","Error al guardar");toast(e.message)}}finally{saving.delete(key)}}
async function pushAll(){if(!dirty.size){toast("No hay cambios pendientes");return}for(const key of [...dirty])await saveCollection(key)}
function markDirty(key,autosave=true){dirty.add(key);syncStatus("",`${dirty.size} sección(es) sin guardar`);if(!autosave)return;clearTimeout(saveTimers[key]);saveTimers[key]=setTimeout(()=>saveCollection(key),1800)}
async function reloadCollection(key){const remote=await loadFile(key);if(key==="media")data.media=remote;else data.collections[key]=remote;dirty.delete(key);syncStatus("ok",dirty.size?`${dirty.size} sección(es) pendientes`:"Sincronizado");render();toast(`${labels[key]||key} recargado desde GitHub`)}
function openConnect(msg=""){$("tokenInput").value=token;$("connectError").hidden=!msg;$("connectError").textContent=msg;$("connectBg").hidden=false}
function saveToken(){const v=$("tokenInput").value.trim();if(!v)return;token=v;if($("rememberToken").checked){localStorage.setItem(LOCAL_KEY,v);sessionStorage.removeItem(SESSION_KEY)}else{sessionStorage.setItem(SESSION_KEY,v);localStorage.removeItem(LOCAL_KEY)}$("connectBg").hidden=true;pull()}
function records(key){return data?.collections?.[key]||[]}
function contentRecords(){return Object.entries(data?.collections||{}).filter(([k])=>k!=="conversaciones").flatMap(([,v])=>v)}
function allRecords(){return Object.values(data?.collections||{}).flat()}
function labelFor(key){return data?.collectionMeta?.[key]?.label||labels[key]||key}
function area(r){for(const k of ["Área","Nivel","Sección / tema","Capa","Grupo / capa","Acontecimiento","Tema"]){if(r.fields?.[k])return String(r.fields[k])}return""}
function textOf(r){return r?.fields?.["Enunciado vigente"]||r?.fields?.["Decisión consolidada"]||r?.fields?.["Qué debe resolverse"]||r?.fields?.["Último avance"]||r?.notes||r?.summary||""}
function implicationsOf(r){const found=[];for(const [k,v] of Object.entries(r?.fields||{}))if(v&&/(dependenc|consecuencia|restric|impact|riesgo|afecta|acción siguiente)/i.test(k))found.push(String(v));return found}
function statusOpen(r){return /(abierto|pendiente|pregunta|revis|reformular|exploratoria|propuesta|pospuesto)/.test(norm(r?.status))}
function updatedValue(r){const t=Date.parse(r?.updatedAt||"");return Number.isFinite(t)?t:0}
function relatedRecords(r,limit=5){const words=[...new Set(norm(`${r.title} ${r.summary} ${area(r)}`).split(/[^a-z0-9ñ]+/).filter(w=>w.length>5))];if(!words.length)return[];return contentRecords().filter(x=>x!==r).map(x=>({x,score:words.reduce((s,w)=>s+(norm(JSON.stringify(x)).includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.x)}
function navCounts(){return{escritorio:records("conversaciones").filter(statusOpen).length,decidir:decisionPool().length,canon:records("canon").filter(r=>/canon|restric|confirm|corregid/.test(norm(r.status))).length,biblioteca:data?.media?.length||0}}
function renderNav(){if(!data)return;const counts=navCounts(),items=[
  {key:"escritorio",label:"Escritorio del autor",icon:"⌂"},
  {key:"decidir",label:"Decidir",icon:"✓"},
  {key:"canon",label:"Canon",icon:"◫"},
  {key:"biblioteca",label:"Biblioteca",icon:"▦"}
];$("nav").innerHTML=items.map(x=>`<button class="${active===x.key?"active":""}" data-nav="${x.key}"><span class="nav-icon">${x.icon}</span><b>${x.label}</b>${counts[x.key]?`<span class="count">${counts[x.key]}</span>`:"<span></span>"}</button>`).join("");document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{active=b.dataset.nav;$("sidebar").classList.remove("open");$("search").value="";render()})}
function setHead(eyebrow,title,desc,newLabel="Nuevo"){$("eyebrow").textContent=eyebrow;$("title").textContent=title;$("desc").textContent=desc;$("newBtn").textContent=newLabel}
function render(){if(!data)return;renderNav();const q=$("search").value.trim();if(q)return renderSearch(q);if(active==="escritorio")renderDesk();else if(active==="decidir")renderDecide();else if(active==="canon")renderCanon();else renderLibrary()}
function renderSearch(q){setHead("Búsqueda global",`Resultados para “${q}”`,"Coincidencias en todo el proyecto.","Nuevo");const hits=allRecords().filter(r=>norm(JSON.stringify(r)).includes(norm(q))).slice(0,80);$("view").innerHTML=`<div class="search-results">${hits.map(r=>`<article class="search-hit" data-open-record="${esc(r.collection)}|${esc(r.id)}"><small>${esc(labelFor(r.collection))} · ${esc(r.id)}</small><strong>${esc(r.title)}</strong><p>${esc(r.summary||textOf(r))}</p></article>`).join("")||'<div class="empty-state">No hay coincidencias.</div>'}</div>`;bindRecordLinks()}
function renderDesk(){setHead("Escritorio del autor","Tu mundo, con espacio para pensar","Lo urgente a la vista; el resto, disponible cuando haga falta.","Nueva conversación");const conversations=records("conversaciones").filter(statusOpen).sort((a,b)=>updatedValue(b)-updatedValue(a));const decisions=decisionPool();const alerts=records("auditoria").filter(r=>statusOpen(r)||norm(r.priority)==="alta").slice(0,5);const recent=allRecords().filter(r=>updatedValue(r)>0).sort((a,b)=>updatedValue(b)-updatedValue(a)).slice(0,5);$("view").innerHTML=`
<div class="dashboard-grid">
  <div class="dashboard-stack">
    <section class="panel">
      <div class="panel-head"><div><h2 class="section-title">Conversaciones abiertas</h2><p class="section-sub">Ideas que todavía pueden cambiar.</p></div><button class="btn small soft-lavender" data-new-conversation>Nueva</button></div>
      <div class="panel-body">${conversations.length?conversations.slice(0,7).map(r=>`<div class="conversation-row"><div class="row-copy"><strong>${esc(r.title)}</strong><span>${esc(r.summary||r.fields?.["Último avance"]||"Sin avance registrado")}</span></div><div class="inline-actions"><span class="pill info">${esc(r.status)}</span><button class="btn small" data-open-record="conversaciones|${esc(r.id)}">Abrir</button>${norm(r.status).includes("exploratoria")?`<button class="btn small soft-sage" data-convert="${esc(r.id)}">Convertir en propuesta</button>`:""}</div></div>`).join(""):'<div class="empty-state">Todavía no hay conversaciones exploratorias abiertas.</div>'}</div>
    </section>
    <section class="panel">
      <div class="panel-head"><div><h2 class="section-title">Atención narrativa</h2><p class="section-sub">Solo alertas con una acción concreta.</p></div><button class="btn small" data-go="decidir">Revisar decisiones</button></div>
      <div class="panel-body">${alerts.length?alerts.map(r=>`<div class="attention-row"><div class="row-copy"><strong>${esc(r.title)}</strong><span>${esc(r.summary||textOf(r))}</span></div><span class="pill ${norm(r.priority)==="alta"?"high":"open"}">${esc(r.priority||r.status||"Revisar")}</span></div>`).join(""):'<div class="empty-state">No hay alertas relevantes.</div>'}</div>
    </section>
  </div>
  <div class="dashboard-stack">
    <article class="calm-card sage"><div class="big-number">${decisions.length}</div><h3>decisiones por resolver</h3><p>Preguntas listas para aceptar, reformular, posponer o descartar.</p><button class="btn primary" data-go="decidir">Continuar decidiendo</button></article>
    <article class="calm-card mist"><h3>Último contenido trabajado</h3>${recent.length?recent.map(r=>`<div class="recent-row"><div class="row-copy"><strong>${esc(r.title)}</strong><span>${esc(labelFor(r.collection))}</span></div><button class="btn small" data-open-record="${esc(r.collection)}|${esc(r.id)}">Abrir</button></div>`).join(""):'<p>No hay cambios recientes registrados.</p>'}</article>
    <article class="calm-card peach"><h3>Canal conversacional</h3><p>Las ideas detectadas pueden entrar como propuesta. El canon solo cambia mediante aprobación explícita.</p><span class="pill good">Estructura preparada</span></article>
  </div>
</div>`;bindCommon();document.querySelectorAll("[data-new-conversation]").forEach(b=>b.onclick=newConversation);document.querySelectorAll("[data-convert]").forEach(b=>b.onclick=()=>convertConversation(b.dataset.convert))}
function decisionPool(){const pending=records("pendientes").filter(r=>!/(aprobado e incorporado|descartado|cerrado)/.test(norm(r.status)));const proposals=records("conversaciones").filter(r=>/(propuesta|lista para decidir)/.test(norm(r.status)));return [...pending,...proposals]}
function renderDecide(){setHead("Decidir","Resolver sin perder el hilo","Una pregunta por vez, con sus implicancias visibles.","Nueva propuesta");const pool=decisionTab==="exploraciones"?records("conversaciones").filter(r=>statusOpen(r)):decisionPool();if(!pool.find(r=>r.id===activeDecisionId))activeDecisionId=pool[0]?.id||"";const current=pool.find(r=>r.id===activeDecisionId);$("view").innerHTML=`<div class="tabs"><button class="tab ${decisionTab==="decisiones"?"active":""}" data-decision-tab="decisiones">Para decidir</button><button class="tab ${decisionTab==="exploraciones"?"active":""}" data-decision-tab="exploraciones">Exploraciones</button></div><div class="decision-layout"><aside class="decision-list">${pool.map(r=>`<button class="decision-item ${r.id===activeDecisionId?"active":""}" data-decision-id="${esc(r.id)}"><strong>${esc(r.title)}</strong><span>${esc(r.status||r.priority||"")}</span></button>`).join("")||'<div class="empty-state">No hay elementos en esta bandeja.</div>'}</aside><main>${current?decisionSheet(current):'<div class="decision-sheet empty-state">Todo resuelto por ahora.</div>'}</main></div>`;document.querySelectorAll("[data-decision-tab]").forEach(b=>b.onclick=()=>{decisionTab=b.dataset.decisionTab;activeDecisionId="";renderDecide()});document.querySelectorAll("[data-decision-id]").forEach(b=>b.onclick=()=>{activeDecisionId=b.dataset.decisionId;renderDecide()});bindDecisionActions(current)}
function decisionSheet(r){const impacts=[...implicationsOf(r),...relatedRecords(r,4).map(x=>`${labelFor(x.collection)} · ${x.title}`)].slice(0,7);const isExploration=r.collection==="conversaciones"&&norm(r.status).includes("exploratoria");return`<article class="decision-sheet"><div class="eyebrow">${esc(labelFor(r.collection))} · ${esc(r.id)}</div><h2 class="decision-question">${esc(r.title)}</h2><p class="decision-context">${esc(r.summary||textOf(r)||"Sin contexto registrado.")}</p><div class="decision-block"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h3>Lo que se me ocurre</h3><span class="pill info">Se guarda automáticamente</span></div><textarea id="decisionIdea" placeholder="Escribí acá una idea, una alternativa, una duda o una formulación posible…" style="width:100%;min-height:180px;margin-top:12px;padding:16px 18px;border:1px solid var(--line);border-radius:16px;background:var(--lavender);color:var(--text);resize:vertical;outline:none;line-height:1.65">${esc(r.notes||"")}</textarea><p class="section-sub">Puede quedar incompleto. No pasa al canon hasta que lo aceptes explícitamente.</p></div><div class="decision-block"><h3>Implicancias y relaciones</h3><div class="impact-list">${impacts.length?impacts.map(x=>`<div class="impact-item">${esc(x)}</div>`).join(""):'<div class="impact-item">No se detectaron implicancias explícitas todavía.</div>'}</div></div><div class="decision-actions">${isExploration?`<button class="btn primary" data-action="convert">Convertir en propuesta</button><button class="btn" data-action="edit">Seguir explorando</button><button class="btn danger" data-action="discard">Archivar</button>`:`<button class="btn primary" data-action="accept">Aceptar para el canon</button><button class="btn soft-lavender" data-action="edit">Reformular</button><button class="btn soft-peach" data-action="postpone">Posponer</button><button class="btn danger" data-action="discard">Descartar</button>`}</div></article>`}
function bindDecisionActions(r){if(!r)return;const idea=$("decisionIdea");if(idea)idea.oninput=()=>{r.notes=idea.value;r.updatedAt=new Date().toISOString();markDirty(r.collection)};document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==="accept")acceptToCanon(r);else if(a==="edit")openRecord(r.collection,r.id);else if(a==="postpone")setDecisionStatus(r,"Pospuesto");else if(a==="discard")discardDecision(r);else if(a==="convert")convertConversation(r.id)})}
function inferCanonSection(r){const n=norm(`${r.title} ${r.summary} ${area(r)} ${textOf(r)}`);if(n.includes("custodio")||/(personaje|caballero|princesa|contemplativo|protagonista)/.test(n))return"Personajes";if(/lugar|mapa|ciudad|ruta|territorio|celum/.test(n))return"Mapa y lugares";if(/civiliz|cultura|pueblo/.test(n))return"Civilizaciones";if(/libro|trilog|escena|climax|giro/.test(n))return"Libros";if(/cronolog|tiempo|secuencia|antes|despues/.test(n))return"Cronología";if(/concordancia|cosmolog|magia|biblioteca|ontolog/.test(n))return"Cosmología y Concordancia";if(/restric|limite|prohib|no puede/.test(n))return"Restricciones narrativas";return"Premisa y mundo"}
function nextCanonId(){const nums=records("canon").map(r=>Number(String(r.id).match(/\d+/)?.[0]||0));return`C${String(Math.max(0,...nums)+1).padStart(3,"0")}`}
function acceptToCanon(r){const statement=(r.notes||r.fields?.["Decisión consolidada"]||r.fields?.["Último avance"]||r.summary||"").trim();if(!statement){toast("Primero escribí una formulación concreta");$("decisionIdea")?.focus();return}const section=inferCanonSection(r);const msg=`Se incorporará al canon:\n\n“${statement}”\n\nDestino: Canon → ${section}\n\n¿Confirmás esta formulación?`;if(!confirm(msg))return;const id=nextCanonId(),entry={id,collection:"canon",title:r.title,summary:statement,status:"Canon confirmado",priority:r.priority||"",notes:"",fields:{ID:id,"Área":section,"Estado maestro":"Canon confirmado","Enunciado vigente":statement,"Decisión del autor":"Confirmar","Precisión / corrección":"","Prioridad":r.priority||"","Dependencias y consecuencias":implicationsOf(r).join(" "),"Fuente":`${labelFor(r.collection)} ${r.id}`},starred:false,updatedAt:new Date().toISOString()};records("canon").push(entry);r.status="Aprobado e incorporado";if(r.fields?.Estado!==undefined)r.fields.Estado=r.status;if(r.fields?.["Estado maestro"]!==undefined)r.fields["Estado maestro"]=r.status;r.updatedAt=new Date().toISOString();markDirty("canon");markDirty(r.collection);canonSection=section;activeDecisionId="";render();toast("Decisión incorporada al canon")}
function setDecisionStatus(r,status){r.status=status;if(r.fields?.Estado!==undefined)r.fields.Estado=status;if(r.fields?.["Estado maestro"]!==undefined)r.fields["Estado maestro"]=status;r.updatedAt=new Date().toISOString();markDirty(r.collection);render();toast(`Estado: ${status}`)}
function discardDecision(r){if(!confirm(`¿Descartar “${r.title}”?`))return;setDecisionStatus(r,r.collection==="conversaciones"?"Archivada":"Descartado")}
function convertConversation(id){const r=records("conversaciones").find(x=>String(x.id)===String(id));if(!r)return;r.status="Propuesta";r.updatedAt=new Date().toISOString();markDirty("conversaciones");active="decidir";decisionTab="decisiones";activeDecisionId=r.id;render();toast("Conversación convertida en propuesta")}
const CANON_SECTIONS=["Premisa y mundo","Cosmología y Concordancia","Personajes","Civilizaciones","Mapa y lugares","Cronología","Libros","Restricciones narrativas"];
function classifyCanon(r){const n=norm(`${r.title} ${r.summary} ${r.status} ${area(r)} ${textOf(r)}`);if(n.includes("custodio")||/(personaje|caballero|princesa|contemplativo|protagonista|antagonista)/.test(n))return"Personajes";if(/lugar|mapa|ciudad|ruta|territorio|geograf|celum/.test(n))return"Mapa y lugares";if(/civiliz|cultura|pueblo|sociedad|vegetal|antropomorf/.test(n))return"Civilizaciones";if(/libro|trilog|escena|climax|giro|volumen/.test(n))return"Libros";if(/cronolog|tiempo|secuencia|fecha|duracion/.test(n))return"Cronología";if(/restric|limite|prohib|no hay|no puede|stakes/.test(n)||norm(r.status).includes("restric"))return"Restricciones narrativas";if(/concordancia|cosmolog|magia|biblioteca|ontolog|voluntad magica/.test(n))return"Cosmología y Concordancia";return"Premisa y mundo"}
function canonicalEntries(){return records("canon").filter(r=>!/(descartado|obsoleto)/.test(norm(r.status)))}
function renderCanon(){setHead("Canon consolidado","La verdad vigente del mundo","Lectura orgánica, con la trazabilidad disponible solo cuando la necesitás.",canonSection==="Mapa y lugares"?"Subir mapa":"Nuevo fragmento");const entries=canonicalEntries(),groups=Object.fromEntries(CANON_SECTIONS.map(s=>[s,entries.filter(r=>classifyCanon(r)===s)]));const current=groups[canonSection]||[];$("view").innerHTML=`<div class="canon-layout"><aside class="canon-index">${CANON_SECTIONS.map(s=>`<button class="${s===canonSection?"active":""}" data-canon-section="${esc(s)}"><span>${esc(s)}</span><span>${groups[s].length}</span></button>`).join("")}</aside><main class="canon-document">${canonSection==="Mapa y lugares"?mapBlock():""}<div class="canon-document-head"><div class="eyebrow">Canon consolidado</div><h2>${esc(canonSection)}</h2><p>${canonSectionDescription(canonSection)}</p></div>${current.length?current.map(canonEntry).join(""):'<div class="empty-state">Todavía no hay contenido consolidado en esta sección.</div>'}</main></div>`;document.querySelectorAll("[data-canon-section]").forEach(b=>b.onclick=()=>{canonSection=b.dataset.canonSection;renderCanon()});bindRecordLinks();bindMap();if(canonSection==="Mapa y lugares")hydrateMedia()}
function canonSectionDescription(s){return({"Premisa y mundo":"Principios generales que sostienen el universo narrativo.","Cosmología y Concordancia":"Reglas profundas del mundo, la magia, la biblioteca y la Concordancia.","Personajes":"Identidades, voluntades, límites y funciones dramáticas. El Custodio vive aquí.","Civilizaciones":"Culturas, sociedades y formas de interpretar el mundo.","Mapa y lugares":"Geografía narrativa, mapas, rutas y lugares creados desde ellos.","Cronología":"Secuencias, antecedentes y relaciones temporales.","Libros":"Arquitectura de la trilogía, conflictos y acontecimientos.","Restricciones narrativas":"Límites que preservan coherencia, tensión y consecuencias."})[s]||""}
function canonEntry(r){const implications=implicationsOf(r);return`<article class="canon-entry"><h3>${esc(r.title)}</h3><div class="canon-text">${esc(textOf(r)||r.summary)}</div>${implications.length?`<div class="consequence"><strong>Implicancia:</strong> ${esc(implications.join(" "))}</div>`:""}<details class="trace"><summary>Ver trazabilidad</summary><p>${esc(r.id)} · ${esc(r.status||"")} · ${esc(r.fields?.Fuente||"Sin fuente registrada")}</p><button class="btn small" data-open-record="canon|${esc(r.id)}">Editar detalle técnico</button></details></article>`}
function mapBlock(){const maps=(data.media||[]).filter(x=>x.kind==="map");if(!selectedMapId||!maps.find(x=>x.id===selectedMapId))selectedMapId=maps[0]?.id||"";const map=maps.find(x=>x.id===selectedMapId);return`<section class="map-panel"><div class="map-toolbar"><div>${maps.length?`<select id="mapSelect">${maps.map(m=>`<option value="${esc(m.id)}" ${m.id===selectedMapId?"selected":""}>${esc(m.title)}</option>`).join("")}</select>`:"<strong>Mapa del mundo</strong>"}</div><button class="btn soft-sage" data-upload-kind="map">Subir mapa</button></div><div class="map-stage" id="mapStage" data-map-id="${esc(map?.id||"")}">${map?`<img data-media-id="${esc(map.id)}" alt="${esc(map.title)}">${(map.markers||[]).map(m=>`<button class="map-marker" style="left:${Number(m.x)||0}%;top:${Number(m.y)||0}%" title="${esc(m.type||"Lugar")}">●<span>${esc(m.label)}</span></button>`).join("")}`:'<div class="map-hint"><strong>Subí un mapa para empezar.</strong><br>Después vas a poder hacer clic sobre él y crear lugares desde la imagen.</div>'}</div>${map?'<p class="section-sub">Hacé clic sobre el mapa para crear un lugar provisional.</p>':""}</section>`}
function bindMap(){document.querySelectorAll("[data-upload-kind]").forEach(b=>b.onclick=()=>startImageUpload(b.dataset.uploadKind));const sel=$("mapSelect");if(sel)sel.onchange=()=>{selectedMapId=sel.value;renderCanon()};const stage=$("mapStage");if(stage&&stage.dataset.mapId)stage.onclick=e=>{if(e.target.closest(".map-marker"))return;const rect=stage.getBoundingClientRect(),x=((e.clientX-rect.left)/rect.width)*100,y=((e.clientY-rect.top)/rect.height)*100;createPlaceFromMap(stage.dataset.mapId,x,y)}}
async function getMediaUrl(item){if(mediaCache.has(item.id))return mediaCache.get(item.id);try{const r=await gh("GET",`${api(item.path)}?ref=${GH.branch}`),url=`data:${item.mime||"image/jpeg"};base64,${r.content.replace(/\n/g,"")}`;mediaCache.set(item.id,url);return url}catch(e){return""}}
async function hydrateMedia(){const nodes=[...document.querySelectorAll("img[data-media-id]")];for(const img of nodes){const item=data.media.find(x=>x.id===img.dataset.mediaId);if(item){const url=await getMediaUrl(item);if(url)img.src=url}}}
async function prepareImage(file,max=1800){const bitmap=await createImageBitmap(file),scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",.86));const buffer=await blob.arrayBuffer();let bin="";for(const b of new Uint8Array(buffer))bin+=String.fromCharCode(b);return{base64:btoa(bin),mime:"image/webp",ext:"webp",width:canvas.width,height:canvas.height}}
function slug(s){return norm(s).replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,50)||"imagen"}
function startImageUpload(kind="reference"){$("imageInput").dataset.kind=kind;$("imageInput").value="";$("imageInput").click()}
async function uploadSelectedImage(file,kind){if(!file)return;if(file.size>12*1024*1024){toast("La imagen supera 12 MB");return}const title=prompt(kind==="map"?"Nombre del mapa":"Título de la imagen",file.name.replace(/\.[^.]+$/,""));if(!title)return;syncStatus("","Procesando imagen…");try{const img=await prepareImage(file),id=`IMG-${Date.now()}`,path=`media/${Date.now()}-${slug(title)}.${img.ext}`;await gh("PUT",api(path),{message:`Atlas del Canon: subir ${kind==="map"?"mapa":"imagen"} ${title}`,content:img.base64,branch:GH.branch});const record={id,kind,title,path,mime:img.mime,width:img.width,height:img.height,relatedTo:[],markers:[],uploadedAt:new Date().toISOString()};data.media.unshift(record);markDirty("media",false);await saveCollection("media");mediaCache.set(id,`data:${img.mime};base64,${img.base64}`);if(kind==="map"){selectedMapId=id;canonSection="Mapa y lugares";active="canon"}else{libraryTab="imagenes";active="biblioteca"}render();toast("Imagen subida al Atlas")}catch(e){syncStatus("bad","Error al subir imagen");toast(e.message)}}
function createPlaceFromMap(mapId,x,y){const map=data.media.find(m=>m.id===mapId);if(!map)return;const name=prompt("Nombre del lugar");if(!name)return;const type=prompt("Tipo de lugar (ciudad, región, ruina, paso…)","Lugar")||"Lugar";const description=prompt("Descripción breve","")||"";const canonId=nextCanonId(),marker={id:`M-${Date.now()}`,label:name,type,x:Number(x.toFixed(3)),y:Number(y.toFixed(3)),canonId};map.markers=map.markers||[];map.markers.push(marker);records("canon").push({id:canonId,collection:"canon",title:name,summary:description||`${type} creado desde el mapa ${map.title}.`,status:"Provisional",priority:"",notes:"",fields:{ID:canonId,"Área":"Mapa y lugares","Estado maestro":"Provisional","Enunciado vigente":description||`${name} es un ${type.toLowerCase()} ubicado en ${map.title}.`,"Decisión del autor":"Pendiente de confirmar","Precisión / corrección":"","Prioridad":"","Dependencias y consecuencias":"","Fuente":`Mapa ${map.title}`,"Mapa":map.id,"Coordenada X":String(marker.x),"Coordenada Y":String(marker.y)},starred:false,updatedAt:new Date().toISOString()});markDirty("media");markDirty("canon");renderCanon();toast("Lugar provisional creado desde el mapa")}
function renderLibrary(){setHead("Biblioteca","Materiales y memoria del proyecto","Imágenes, fuentes, historial y acceso técnico sin recargar la navegación.",libraryTab==="imagenes"?"Subir imagen":"Nuevo registro");$("view").innerHTML=`<div class="tabs"><button class="tab ${libraryTab==="imagenes"?"active":""}" data-library-tab="imagenes">Imágenes</button><button class="tab ${libraryTab==="fuentes"?"active":""}" data-library-tab="fuentes">Fuentes</button><button class="tab ${libraryTab==="historial"?"active":""}" data-library-tab="historial">Historial</button><button class="tab ${libraryTab==="tecnico"?"active":""}" data-library-tab="tecnico">Modo técnico</button></div>${libraryBody()}`;document.querySelectorAll("[data-library-tab]").forEach(b=>b.onclick=()=>{libraryTab=b.dataset.libraryTab;renderLibrary()});bindCommon();document.querySelectorAll("[data-upload-kind]").forEach(b=>b.onclick=()=>startImageUpload(b.dataset.uploadKind));document.querySelectorAll("[data-tech-col]").forEach(b=>b.onclick=()=>{techCollection=b.dataset.techCol;renderLibrary()});hydrateMedia()}
function libraryBody(){if(libraryTab==="imagenes")return`<div class="library-toolbar"><p class="section-sub">Mapas, personajes, lugares, objetos y referencias visuales.</p><button class="btn primary" data-upload-kind="reference">Subir imagen</button></div><div class="library-grid">${data.media.length?data.media.map(m=>`<article class="library-card"><div class="library-thumb"><img data-media-id="${esc(m.id)}" alt="${esc(m.title)}"></div><div class="copy"><strong>${esc(m.title)}</strong><span>${m.kind==="map"?"Mapa":"Referencia visual"}${m.markers?.length?` · ${m.markers.length} lugares`:""}</span></div></article>`).join(""):'<div class="empty-state">Todavía no hay imágenes. La primera puede ser el mapa del mundo.</div>'}</div>`;if(libraryTab==="fuentes"){const rs=records("integracion");return`<section class="panel"><div class="panel-head"><h2 class="section-title">Fuentes y documentos</h2></div><div class="panel-body">${rs.map(r=>`<div class="recent-row"><div class="row-copy"><strong>${esc(r.title)}</strong><span>${esc(r.summary)}</span></div><button class="btn small" data-open-record="integracion|${esc(r.id)}">Abrir</button></div>`).join("")||'<div class="empty-state">No hay fuentes registradas.</div>'}</div></section>`}if(libraryTab==="historial"){const rs=allRecords().filter(r=>updatedValue(r)>0).sort((a,b)=>updatedValue(b)-updatedValue(a));return`<section class="panel"><div class="panel-head"><h2 class="section-title">Cambios recientes</h2></div><div class="panel-body">${rs.map(r=>`<div class="recent-row"><div class="row-copy"><strong>${esc(r.title)}</strong><span>${esc(labelFor(r.collection))} · ${new Date(r.updatedAt).toLocaleString("es-AR")}</span></div><button class="btn small" data-open-record="${esc(r.collection)}|${esc(r.id)}">Abrir</button></div>`).join("")||'<div class="empty-state">Todavía no hay historial fechado.</div>'}</div></section>`}const cols=Object.keys(data.collections);const rs=records(techCollection);return`<section class="technical-shell"><div class="tech-toolbar">${cols.map(c=>`<button class="tech-chip ${techCollection===c?"active":""}" data-tech-col="${esc(c)}">${esc(labelFor(c))} · ${rsFor(c)}</button>`).join("")}</div><div class="records">${rs.map(recordCard).join("")||'<div class="empty-state">Esta colección está vacía.</div>'}</div></section>`}
function rsFor(c){return records(c).length}
function recordCard(r){return`<article class="record-card" data-open-record="${esc(r.collection)}|${esc(r.id)}"><div class="rid">${esc(r.id)}</div><h3>${esc(r.title)}</h3><p>${esc(r.summary||textOf(r)||"Sin resumen")}</p><div class="meta">${r.status?`<span class="pill ${statusOpen(r)?"open":"good"}">${esc(r.status)}</span>`:""}${r.priority?`<span class="pill ${norm(r.priority)==="alta"?"high":"info"}">${esc(r.priority)}</span>`:""}</div></article>`}
function bindCommon(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{active=b.dataset.go;$("search").value="";render()});bindRecordLinks()}
function bindRecordLinks(){document.querySelectorAll("[data-open-record]").forEach(n=>n.onclick=e=>{e.stopPropagation();const [col,id]=n.dataset.openRecord.split("|");openRecord(col,id)})}
function openRecord(col,id){const r=records(col).find(x=>String(x.id)===String(id));if(!r)return;editing={col,id};$("recordEyebrow").textContent=labelFor(col);$("recordTitle").textContent=r.title||r.id;const top=[["__id","ID",r.id],["__title","Título",r.title],["__summary","Resumen",r.summary],["__status","Estado",r.status],["__priority","Prioridad",r.priority],["__notes","Notas",r.notes||""]],fields=[...top,...Object.entries(r.fields||{}).filter(([k])=>!top.some(([x])=>x===k)).map(([k,v])=>[k,k,v])];$("recordForm").innerHTML=`<div class="form-grid">${fields.map(([k,l,v])=>{const long=String(v??"").length>95||/enunciado|problema|soluci|consecuencia|precisi|dependencia|decisi|acción|función|riesgo|ajustes|fuente|avance|tema/i.test(l);return`<div class="field ${long?"full":""}"><label>${esc(l)}</label>${long?`<textarea name="${esc(k)}">${esc(v)}</textarea>`:`<input name="${esc(k)}" value="${esc(v)}">`}</div>`}).join("")}</div>`;$("recordBg").hidden=false}
function saveRecord(e){e.preventDefault();if(!editing)return;const r=records(editing.col).find(x=>String(x.id)===String(editing.id)),f=new FormData($("recordForm"));r.id=String(f.get("__id")||r.id).trim();r.title=String(f.get("__title")||r.id).trim();r.summary=String(f.get("__summary")||"").trim();r.status=String(f.get("__status")||"").trim();r.priority=String(f.get("__priority")||"").trim();r.notes=String(f.get("__notes")||"").trim();Object.keys(r.fields||{}).forEach(k=>{if(f.has(k))r.fields[k]=String(f.get(k)||"")});r.updatedAt=new Date().toISOString();const col=editing.col;$("recordBg").hidden=true;editing=null;markDirty(col);render();toast("Registro actualizado")}
function newConversation(){const title=prompt("Tema de la conversación exploratoria");if(!title)return;const summary=prompt("¿Qué querés explorar?","")||"";const id=`X${String(Date.now()).slice(-7)}`,r={id,collection:"conversaciones",title,summary,status:"Exploratoria",priority:"",notes:"",fields:{Tema:title,"Último avance":summary,"Elementos relacionados":"","Fuente":"Conversación del autor"},starred:false,updatedAt:new Date().toISOString()};records("conversaciones").unshift(r);markDirty("conversaciones");render();toast("Conversación exploratoria creada")}
function newGeneric(){const col=libraryTab==="tecnico"?techCollection:"canon",id=col==="canon"?nextCanonId():`NUEVO-${Date.now().toString().slice(-6)}`,r={id,collection:col,title:"Nuevo registro",summary:"",status:col==="canon"?"Provisional":"Pendiente",priority:"",notes:"",fields:col==="canon"?{ID:id,"Área":canonSection,"Estado maestro":"Provisional","Enunciado vigente":"","Decisión del autor":"Pendiente","Precisión / corrección":"","Prioridad":"","Dependencias y consecuencias":"","Fuente":"Creación manual"}:{},starred:false,updatedAt:new Date().toISOString()};records(col).unshift(r);markDirty(col);openRecord(col,id);render()}
function delRecord(e){e.preventDefault();if(!editing)return;const arr=records(editing.col),i=arr.findIndex(x=>String(x.id)===String(editing.id));if(i<0||!confirm(`¿Eliminar ${arr[i].id} · ${arr[i].title}?`))return;const col=editing.col;arr.splice(i,1);$("recordBg").hidden=true;editing=null;markDirty(col);render();toast("Registro eliminado")}
function newByContext(){if(active==="escritorio")newConversation();else if(active==="decidir"){decisionTab="exploraciones";newConversation()}else if(active==="canon"&&canonSection==="Mapa y lugares")startImageUpload("map");else if(active==="biblioteca"&&libraryTab==="imagenes")startImageUpload("reference");else newGeneric()}
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).hidden=true);
$("connectBtn").onclick=saveToken;$("settingsBtn").onclick=()=>openConnect();$("pullBtn").onclick=()=>{if(dirty.size&&!confirm("Hay cambios sin guardar. ¿Recargar de todos modos?"))return;pull()};$("pushBtn").onclick=pushAll;$("conflictPull").onclick=()=>{$("conflictBg").hidden=true;reloadCollection(conflictKey)};$("conflictForce").onclick=()=>saveCollection(conflictKey,true);$("recordForm").onsubmit=saveRecord;$("deleteBtn").onclick=delRecord;$("newBtn").onclick=newByContext;$("search").oninput=render;$("themeBtn").onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem(THEME_KEY,t)};$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");$("imageInput").onchange=e=>uploadSelectedImage(e.target.files?.[0],e.target.dataset.kind||"reference");document.documentElement.dataset.theme=localStorage.getItem(THEME_KEY)||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");window.addEventListener("beforeunload",e=>{if(dirty.size){e.preventDefault();e.returnValue=""}});token?pull():openConnect();
})();
