(()=>{"use strict";
const GH={owner:"Agent75-ai",repo:"atlas-canon-data",branch:"main"};
const FILES={meta:"meta.json",canon:"canon.json",decisiones:"decisiones.json",pendientes:"pendientes.json",auditoria:"auditoria.json",integracion:"integracion.json",concordancia:"concordancia.json",civilizaciones:"civilizaciones.json",libro1:"libro1.json"};
const SESSION_KEY="atlas-gh-token-session",LOCAL_KEY="atlas-gh-token-local",THEME_KEY="atlas-theme";
let token=sessionStorage.getItem(SESSION_KEY)||localStorage.getItem(LOCAL_KEY)||"";
let data=null,shas={},active="dashboard",editing=null,dirty=new Set(),saving=new Set(),saveTimers={},conflictKey="";
const $=id=>document.getElementById(id),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"),norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(),clone=v=>JSON.parse(JSON.stringify(v));
const api=path=>`https://api.github.com/repos/${GH.owner}/${GH.repo}/contents/${path}`;
function decodeGitHubBase64(s){const bytes=Uint8Array.from(atob(s.replace(/\n/g,"")),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encodeGitHubBase64(s){const bytes=new TextEncoder().encode(s);let bin="";for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin)}
async function gunzipB64(s){const bytes=Uint8Array.from(atob(s),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));return new Response(stream).text()}
async function gzipB64(s){const stream=new Blob([new TextEncoder().encode(s)]).stream().pipeThrough(new CompressionStream("gzip"));const buf=await new Response(stream).arrayBuffer();let bin="";for(const b of new Uint8Array(buf))bin+=String.fromCharCode(b);return btoa(bin)}
function toast(m){const n=document.createElement("div");n.className="toast";n.textContent=m;$("toasts").append(n);setTimeout(()=>n.remove(),2800)}
function syncStatus(kind,text){$("syncDot").className=`dot ${kind||""}`;$("syncText").textContent=text}
async function gh(method,url,body){let last;for(let attempt=0;attempt<3;attempt++){try{const headers={Authorization:`token ${token}`,...(body?{"Content-Type":"application/json"}:{})};const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined,cache:"no-store",mode:"cors"});if(!r.ok){const e=await r.json().catch(()=>({message:r.statusText}));const err=new Error(e.message||`GitHub ${r.status}`);err.status=r.status;throw err}return r.json()}catch(e){last=e;if(e.status)throw e;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,700*(attempt+1)))}}throw new Error(`No se pudo conectar con GitHub: ${last?.message||"error de red"}`)}
async function loadFile(key){const path=FILES[key],r=await gh("GET",`${api(path)}?ref=${GH.branch}`),text=decodeGitHubBase64(r.content),obj=JSON.parse(text);shas[key]=r.sha;return obj}
async function pull(){if(!token)return openConnect();syncStatus("","Cargando desde GitHub…");try{const entries=[];for(const key of Object.keys(FILES)){syncStatus("",`Cargando ${key}…`);entries.push([key,await loadFile(key)])}const map=Object.fromEntries(entries),meta=map.meta;data={...meta,collections:{}};for(const key of Object.keys(FILES))if(key!=="meta")data.collections[key]=map[key];dirty.clear();syncStatus("ok","Sincronizado");render();toast("Canon cargado desde GitHub")}catch(e){syncStatus("bad","Error de conexión");if(e.status===401||e.status===403){token="";sessionStorage.removeItem(SESSION_KEY);localStorage.removeItem(LOCAL_KEY);openConnect(`GitHub rechazó el token: ${e.message}`)}else openConnect(e.message)}}
async function saveCollection(key,force=false){if(!data||!token||saving.has(key)||(!dirty.has(key)&&!force))return;saving.add(key);syncStatus("",`Guardando ${data.collectionMeta[key]?.label||key}…`);try{let useSha=shas[key];if(force){const latest=await gh("GET",`${api(FILES[key])}?ref=${GH.branch}`);useSha=latest.sha}const text=JSON.stringify(data.collections[key],null,2);const r=await gh("PUT",api(FILES[key]),{message:`Atlas del Canon: ${data.collectionMeta[key]?.label||key} · ${new Date().toLocaleString("es-AR")}`,content:encodeGitHubBase64(text),sha:useSha,branch:GH.branch});shas[key]=r.content.sha;dirty.delete(key);syncStatus("ok",dirty.size?`${dirty.size} sección(es) pendientes`:"Sincronizado");if(conflictKey===key){conflictKey="";$("conflictBg").hidden=true}toast(`${data.collectionMeta[key]?.label||key} guardado en GitHub`)}catch(e){if(e.status===409||e.status===422){conflictKey=key;syncStatus("bad","Conflicto de versión");$("conflictBg").hidden=false}else{syncStatus("bad","Error al guardar");toast(e.message)}}finally{saving.delete(key)}}
async function pushAll(){if(!dirty.size){toast("No hay cambios pendientes");return}for(const key of [...dirty])await saveCollection(key)}
function markDirty(key){dirty.add(key);syncStatus("",`${dirty.size} sección(es) sin guardar`);clearTimeout(saveTimers[key]);saveTimers[key]=setTimeout(()=>saveCollection(key),1800)}
async function reloadCollection(key){const remote=await loadFile(key);data.collections[key]=remote;dirty.delete(key);syncStatus("ok",dirty.size?`${dirty.size} sección(es) pendientes`:"Sincronizado");render();toast(`${data.collectionMeta[key]?.label||key} recargado desde GitHub`)}
function openConnect(msg=""){$("tokenInput").value=token;$("connectError").hidden=!msg;$("connectError").textContent=msg;$("connectBg").hidden=false}
function saveToken(){const v=$("tokenInput").value.trim();if(!v)return;token=v;if($("rememberToken").checked){localStorage.setItem(LOCAL_KEY,v);sessionStorage.removeItem(SESSION_KEY)}else{sessionStorage.setItem(SESSION_KEY,v);localStorage.removeItem(LOCAL_KEY)}$("connectBg").hidden=true;pull()}
function allRecords(){return data?Object.values(data.collections||{}).flat():[]}
function records(key){return key==="todos"?allRecords():data?.collections?.[key]||[]}
function meta(key){return key==="todos"?{label:"Resultados globales",description:"Coincidencias en todas las secciones."}:data.collectionMeta[key]}
function renderNav(){if(!data)return;const items=[{key:"dashboard",label:"Panel general",count:allRecords().length},...Object.entries(data.collectionMeta).map(([key,m])=>({key,label:m.label,count:records(key).length}))];$("nav").innerHTML=items.map(x=>`<button class="${x.key===active?"active":""}" data-nav="${x.key}"><b>${esc(x.label)}</b><span class="count">${x.count}</span></button>`).join("");document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{active=b.dataset.nav;$("sidebar").classList.remove("open");resetFilters();render()})}
function render(){if(!data)return;renderNav();active==="dashboard"?renderDashboard():renderCollection()}
function renderDashboard(){$("dashboard").hidden=false;$("collection").hidden=true;$("eyebrow").textContent="Panel general";$("title").textContent="Estado del proyecto";$("desc").textContent="Canon, decisiones y continuidad en una única fuente versionada.";const all=allRecords(),canon=records("canon"),confirmed=canon.filter(r=>norm(r.status).includes("canon confirmado")).length,restr=canon.filter(r=>norm(r.status).includes("restric")).length,open=all.filter(r=>/(abierto|pendiente|pregunta|revis|reformular)/.test(norm(r.status))).length,high=all.filter(r=>norm(r.priority)==="alta").length,focus=records("pendientes").filter(r=>norm(r.priority)==="alta"||norm(r.status).includes("abierto")).slice(0,6);$("dashboard").innerHTML=`<div class="kpis">${[["Canon confirmado",confirmed,`${canon.length} entradas`],["Restricciones",restr,"límites operativos"],["Abiertos o en revisión",open,"requieren desarrollo"],["Alta prioridad",high,"registros críticos"]].map(x=>`<article class="kpi"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join("")}</div><div class="grid2"><section class="panel"><div class="panel-head"><h2>Foco inmediato</h2><button class="btn small" data-open="pendientes">Ver todos</button></div><div class="panel-body focus">${focus.map(r=>`<article class="focus-item" data-rec="${esc(r.id)}" data-col="pendientes"><strong>${esc(r.id)} · ${esc(r.title)}</strong><span>${esc(r.summary)}</span></article>`).join("")||"Sin pendientes críticos"}</div></section><section class="quote"><blockquote>“El Custodio no altera voluntades: fuerza al mundo hacia equilibrios artificiales que considera válidos.”</blockquote></section><section class="panel"><div class="panel-head"><h2>Accesos rápidos</h2></div><div class="panel-body focus"><article class="focus-item" data-open="concordancia"><strong>Concordancia</strong><span>Núcleo confirmado, hipótesis y vacíos.</span></article><article class="focus-item" data-open="civilizaciones"><strong>Civilizaciones</strong><span>Interfaces narrativas y materialidad.</span></article><article class="focus-item" data-open="libro1"><strong>Libro I</strong><span>Ruta recuperada y compatibilidad.</span></article></div></section></div>`;document.querySelectorAll("[data-open]").forEach(n=>n.onclick=()=>{active=n.dataset.open;render()});document.querySelectorAll("[data-rec]").forEach(n=>n.onclick=()=>openRecord(n.dataset.col,n.dataset.rec))}
function fill(sel,label,vals){const cur=sel.value;sel.innerHTML=`<option value="">${label}</option>`+vals.map(v=>`<option>${esc(v)}</option>`).join("");if(vals.includes(cur))sel.value=cur}
function area(r){for(const k of ["Área","Nivel","Sección / tema","Capa","Grupo / capa","Acontecimiento"]){if(r.fields?.[k])return String(r.fields[k])}return""}
function filtered(){const q=norm($("search").value);return records(active).filter(r=>(!q||norm(JSON.stringify(r)).includes(q))&&(!$('statusF').value||r.status===$('statusF').value)&&(!$('priorityF').value||r.priority===$('priorityF').value)&&(!$('areaF').value||area(r)===$('areaF').value)).sort((a,b)=>(b.starred?1:0)-(a.starred?1:0)||String(a.id).localeCompare(String(b.id),"es",{numeric:true}))}
function renderCollection(){$("dashboard").hidden=true;$("collection").hidden=false;const m=meta(active);$("eyebrow").textContent=active==="todos"?"Búsqueda global":"Base editorial";$("title").textContent=m.label;$("desc").textContent=m.description;const rs=records(active);fill($("statusF"),"Todos los estados",[...new Set(rs.map(r=>r.status).filter(Boolean))].sort());fill($("priorityF"),"Todas las prioridades",[...new Set(rs.map(r=>r.priority).filter(Boolean))].sort());fill($("areaF"),"Todas las áreas",[...new Set(rs.map(area).filter(Boolean))].sort());const fr=filtered();$("results").textContent=`${fr.length} de ${rs.length}`;$("records").innerHTML=fr.map(card).join("");$("empty").hidden=!!fr.length;document.querySelectorAll(".card").forEach(c=>c.onclick=e=>{if(e.target.closest(".star"))return;openRecord(c.dataset.collection,c.dataset.id)});document.querySelectorAll(".star").forEach(b=>b.onclick=e=>{e.stopPropagation();const c=b.closest(".card"),r=records(c.dataset.collection).find(x=>String(x.id)===String(c.dataset.id));r.starred=!r.starred;markDirty(c.dataset.collection);renderCollection()})}
function sclass(v){const n=norm(v);if(/confirm|fuerte|compatible/.test(n))return"good";if(/abierto|pendiente|pregunta|revis/.test(n))return"open";return""}
function card(r){return`<article class="card" data-id="${esc(r.id)}" data-collection="${esc(r.collection)}"><div class="card-top"><div><div class="rid">${esc(r.id)}</div><div class="rtitle">${esc(r.title)}</div></div><button class="star ${r.starred?"on":""}">${r.starred?"★":"☆"}</button></div><div class="summary">${esc(r.summary||"Sin resumen")}</div><div class="chips">${r.status?`<span class="chip ${sclass(r.status)}">${esc(r.status)}</span>`:""}${r.priority?`<span class="chip ${norm(r.priority)==="alta"?"high":""}">${esc(r.priority)}</span>`:""}${area(r)?`<span class="chip">${esc(area(r))}</span>`:""}</div></article>`}
function openRecord(col,id){const r=records(col).find(x=>String(x.id)===String(id));if(!r)return;editing={col,id};$("recordEyebrow").textContent=meta(col)?.label||col;$("recordTitle").textContent=r.title||r.id;const top=[["__id","ID",r.id],["__title","Título",r.title],["__summary","Resumen",r.summary],["__status","Estado",r.status],["__priority","Prioridad",r.priority],["__notes","Notas",r.notes||""]],fields=[...top,...Object.entries(r.fields||{}).map(([k,v])=>[k,k,v])];$("recordForm").innerHTML=`<div class="form-grid">${fields.map(([k,l,v])=>{const long=String(v??"").length>95||/enunciado|problema|soluci|consecuencia|precisi|dependencia|decisi|acción|función|riesgo|ajustes|fuente/i.test(l);return`<div class="field ${long?"full":""}"><label>${esc(l)}</label>${long?`<textarea name="${esc(k)}">${esc(v)}</textarea>`:`<input name="${esc(k)}" value="${esc(v)}">`}</div>`}).join("")}</div>`;$("recordBg").hidden=false}
function saveRecord(e){e.preventDefault();const r=records(editing.col).find(x=>String(x.id)===String(editing.id)),f=new FormData($("recordForm"));r.id=String(f.get("__id")||r.id).trim();r.title=String(f.get("__title")||r.id).trim();r.summary=String(f.get("__summary")||"").trim();r.status=String(f.get("__status")||"").trim();r.priority=String(f.get("__priority")||"").trim();r.notes=String(f.get("__notes")||"").trim();Object.keys(r.fields||{}).forEach(k=>r.fields[k]=String(f.get(k)||""));r.updatedAt=new Date().toISOString();const col=editing.col;$("recordBg").hidden=true;editing=null;markDirty(col);render();toast("Registro actualizado")}
function newRecord(){const col=(active==="dashboard"||active==="todos")?"canon":active,id=`NUEVO-${Date.now().toString().slice(-6)}`,r={id,collection:col,title:"Nuevo registro",summary:"",status:"Pendiente",priority:"",notes:"",fields:{},starred:false,updatedAt:new Date().toISOString()};data.collections[col].unshift(r);active=col;markDirty(col);render();openRecord(col,id)}
function delRecord(e){e.preventDefault();if(!editing)return;const arr=records(editing.col),i=arr.findIndex(x=>String(x.id)===String(editing.id));if(i<0||!confirm(`¿Eliminar ${arr[i].id} · ${arr[i].title}?`))return;const col=editing.col;arr.splice(i,1);$("recordBg").hidden=true;editing=null;markDirty(col);render();toast("Registro eliminado")}
function resetFilters(){$("search").value="";$("statusF").value="";$("priorityF").value="";$("areaF").value=""}
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).hidden=true);$("connectBtn").onclick=saveToken;$("settingsBtn").onclick=()=>openConnect();$("pullBtn").onclick=()=>{if(dirty.size&&!confirm("Hay cambios sin guardar. ¿Recargar de todos modos?"))return;pull()};$("pushBtn").onclick=pushAll;$("conflictPull").onclick=()=>{$("conflictBg").hidden=true;reloadCollection(conflictKey)};$("conflictForce").onclick=()=>saveCollection(conflictKey,true);$("recordForm").onsubmit=saveRecord;$("deleteBtn").onclick=delRecord;$("newBtn").onclick=newRecord;$("clearF").onclick=()=>{resetFilters();renderCollection()};[$("statusF"),$("priorityF"),$("areaF")].forEach(x=>x.onchange=renderCollection);$("search").oninput=()=>{if(active==="dashboard"&&$("search").value.trim())active="todos";active==="dashboard"?renderDashboard():renderCollection()};$("themeBtn").onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem(THEME_KEY,t)};$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");document.documentElement.dataset.theme=localStorage.getItem(THEME_KEY)||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");window.addEventListener("beforeunload",e=>{if(dirty.size){e.preventDefault();e.returnValue=""}});token?pull():openConnect();
})();
