(()=>{"use strict";
const OWNER="Agent75-ai",REPO="atlas-canon-data",BRANCH="main";
const SESSION_KEY="atlas-gh-token-session",LOCAL_KEY="atlas-gh-token-local";
const state={doc:null,active:"",data:null,loading:null,scheduled:false};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const unique=values=>[...new Set(values.map(v=>String(v||"").trim()).filter(Boolean))];
function token(){return sessionStorage.getItem(SESSION_KEY)||localStorage.getItem(LOCAL_KEY)||""}
function decode(s){const bytes=Uint8Array.from(atob(String(s||"").replace(/\n/g,"")),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function loadJson(path){const headers=token()?{Authorization:`token ${token()}`}:{},url=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}?ref=${BRANCH}`,r=await fetch(url,{headers,cache:"no-store"});if(!r.ok)throw new Error(`No se pudo cargar ${path}`);const body=await r.json();return JSON.parse(decode(body.content))}
async function loadData(){if(state.data)return state.data;if(state.loading)return state.loading;state.loading=Promise.all([loadJson("canon.json"),loadJson("decisiones.json"),loadJson("pendientes.json"),loadJson("civilizaciones.json"),loadJson("libro1.json")]).then(([canon,decisiones,pendientes,civilizaciones,libro1])=>state.data={canon,decisiones,pendientes,civilizaciones,libro1}).finally(()=>state.loading=null);return state.loading}
function injectStyles(){if(document.getElementById("canonNarrativeStyles"))return;const style=document.createElement("style");style.id="canonNarrativeStyles";style.textContent=`
.canon-access{margin:0 0 28px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,var(--surface),color-mix(in srgb,var(--mist) 42%,var(--surface)));overflow:hidden}
.canon-access-head{padding:17px 19px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap}
.canon-access-head strong{font:650 20px Georgia,serif}.canon-access-head span{display:block;color:var(--muted);font-size:12px;margin-top:3px}
.canon-access-actions{display:flex;gap:7px;flex-wrap:wrap}.canon-access-actions button{border:1px solid var(--line);border-radius:99px;background:var(--surface);padding:8px 12px;font-weight:750}.canon-access-actions button:hover,.canon-access-actions button.active{background:var(--sage)}
.canon-access-body{padding:20px}.canon-access[aria-expanded=false] .canon-access-body{display:none}.canon-document.narrative-open>:not(.canon-access){display:none}
.narrative-head{margin-bottom:22px}.narrative-head h2{font:650 clamp(29px,4vw,43px) Georgia,serif}.narrative-head p{color:var(--muted);font-size:16px;max-width:780px}.narrative-toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:18px}.narrative-count{font-size:12px;color:var(--muted)}
.narrative-list{display:grid;gap:10px}.narrative-card{border:1px solid var(--line);border-radius:16px;background:var(--surface);overflow:hidden}.narrative-card>summary{list-style:none;cursor:pointer;padding:14px 16px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:11px}.narrative-card>summary::-webkit-details-marker{display:none}.narrative-card[open]>summary{background:var(--lavender);border-bottom:1px solid var(--line)}.narrative-card summary strong{font:650 18px Georgia,serif}.narrative-card summary small{color:var(--muted)}.narrative-step{min-width:34px;height:34px;border-radius:12px;display:grid;place-items:center;background:var(--mist);font-weight:850;color:var(--sage-strong)}.narrative-status{font-size:11px;border:1px solid var(--line);border-radius:99px;padding:4px 8px;white-space:nowrap}.narrative-content{padding:16px 18px 19px}.narrative-content>p{font:16px/1.65 Georgia,serif;margin:0 0 14px}.narrative-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.narrative-field{padding:11px 12px;border-radius:12px;background:var(--surface2)}.narrative-field.full{grid-column:1/-1}.narrative-field b{display:block;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--sage-strong);margin-bottom:4px}.narrative-field span{color:var(--muted)}
.character-summary{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.character-section{margin-top:16px}.character-section h4{font:650 16px Georgia,serif;margin-bottom:7px}.character-section ul{margin:0;padding-left:20px;color:var(--muted)}.character-section li+li{margin-top:6px}.narrative-empty{padding:35px 18px;text-align:center;color:var(--muted)}
@media(max-width:720px){.narrative-card>summary{grid-template-columns:auto minmax(0,1fr)}.narrative-status{grid-column:2}.narrative-fields{grid-template-columns:1fr}.narrative-field.full{grid-column:auto}}
`;document.head.append(style)}
function isCanon(){return document.getElementById("eyebrow")?.textContent.trim()==="Canon consolidado"&&document.querySelector(".canon-document")}
function schedule(){if(state.scheduled)return;state.scheduled=true;requestAnimationFrame(()=>{state.scheduled=false;ensureAccess()})}
function ensureAccess(){if(!isCanon())return;injectStyles();const doc=document.querySelector(".canon-document");if(state.doc!==doc){state.doc=doc;state.active=""}if(doc.querySelector(".canon-access"))return;const box=document.createElement("section");box.className="canon-access";box.setAttribute("aria-expanded","false");box.innerHTML=`<div class="canon-access-head"><div><strong>Explorar el canon</strong><span>Trama, personajes y características de las civilizaciones, reunidos sin mezclarlo con el modo técnico.</span></div><div class="canon-access-actions"><button data-narrative="trama">Trama</button><button data-narrative="personajes">Personajes</button><button data-narrative="civilizaciones">Civilizaciones</button></div></div><div class="canon-access-body"></div>`;doc.prepend(box);box.querySelectorAll("[data-narrative]").forEach(b=>b.onclick=()=>openNarrative(b.dataset.narrative,box))}
async function openNarrative(kind,box){state.active=kind;state.doc?.classList.add("narrative-open");box.setAttribute("aria-expanded","true");box.querySelectorAll("[data-narrative]").forEach(b=>b.classList.toggle("active",b.dataset.narrative===kind));const body=box.querySelector(".canon-access-body");body.innerHTML=`<div class="narrative-empty">Cargando contenido narrativo…</div>`;try{const data=await loadData();if(state.active!==kind)return;body.innerHTML=`<div class="narrative-toolbar"><button class="btn small" data-return-canon>← Volver al canon</button><span class="narrative-count">Contenido reunido desde las bases vigentes</span></div>${kind==="trama"?renderPlot(data):kind==="civilizaciones"?renderCivilizations(data.civilizaciones):renderCharacters(data)}`;body.querySelector("[data-return-canon]").onclick=()=>closeNarrative(box)}catch(e){body.innerHTML=`<div class="narrative-empty">${esc(e.message)}. Probá recargar la conexión con GitHub.</div>`}}
function closeNarrative(box){state.active="";state.doc?.classList.remove("narrative-open");box.setAttribute("aria-expanded","false");box.querySelectorAll("[data-narrative]").forEach(b=>b.classList.remove("active"));box.querySelector(".canon-access-body").innerHTML=""}
function field(r,name){return r?.fields?.[name]??""}
function plotGeneral(data){const rx=/trama|libro|trilog|cl[ií]max|giro|conflicto|motor irreversible|final|secuencia/i;return [...data.canon,...data.decisiones,...data.pendientes].filter(r=>rx.test(`${r.title} ${r.summary} ${JSON.stringify(r.fields||{})}`)).slice(0,12)}
function renderPlot(data){const general=plotGeneral(data),beats=[...data.libro1].sort((a,b)=>Number(field(a,"Tramo")||999)-Number(field(b,"Tramo")||999));return`<div class="narrative-head"><div class="eyebrow">Canon · Trama</div><h2>Arquitectura narrativa</h2><p>Acceso a la trama general y a la secuencia causal disponible del Libro I. Los vacíos siguen visibles como decisiones necesarias.</p></div>${general.length?`<h3 class="section-title" style="margin-bottom:11px">Trama general</h3><div class="narrative-list" style="margin-bottom:28px">${general.map((r,i)=>simpleRecord(r,i+1)).join("")}</div>`:""}<h3 class="section-title" style="margin-bottom:11px">Libro I · Secuencia causal</h3><div class="narrative-list">${beats.map(plotBeat).join("")||'<div class="narrative-empty">No hay una secuencia de trama disponible.</div>'}</div>`}
function simpleRecord(r,i){const text=field(r,"Enunciado vigente")||field(r,"Decisión consolidada")||field(r,"Qué debe resolverse")||r.summary||"";const consequence=field(r,"Dependencias y consecuencias")||field(r,"Acción siguiente")||field(r,"Jerarquía / restricción");return`<details class="narrative-card"><summary><span class="narrative-step">${i}</span><strong>${esc(r.title)}</strong><span class="narrative-status">${esc(r.status||"Registro")}</span></summary><div class="narrative-content"><p>${esc(text)}</p>${consequence?`<div class="narrative-field full"><b>Implicancia o siguiente paso</b><span>${esc(consequence)}</span></div>`:""}</div></details>`}
function plotBeat(r){const n=field(r,"Tramo")||"·";return`<details class="narrative-card"><summary><span class="narrative-step">${esc(n)}</span><strong>${esc(r.title)}</strong><span class="narrative-status">${esc(r.status||"")}</span></summary><div class="narrative-content"><p>${esc(r.summary||"")}</p><div class="narrative-fields">${nfield("Objetivo material",field(r,"Objetivo material"))}${nfield("Anomalía o pista",field(r,"Anomalía / pista"))}${nfield("Consecuencia causal",field(r,"Consecuencia causal"),true)}${nfield("Civilizaciones o personajes",field(r,"Civilizaciones o personajes"))}${nfield("Decisión necesaria",field(r,"Decisión necesaria"),true)}</div></div></details>`}
function nfield(label,value,full=false){return value?`<div class="narrative-field ${full?"full":""}"><b>${esc(label)}</b><span>${esc(value)}</span></div>`:""}
function renderCivilizations(rows){return`<div class="narrative-head"><div class="eyebrow">Canon · Civilizaciones</div><h2>Características de las civilizaciones</h2><p>Cada ficha reúne conocimiento, materialidad, función narrativa, relación con la biblioteca, riesgos de reducción y vacíos todavía abiertos.</p></div><div class="narrative-list">${rows.map((r,i)=>`<details class="narrative-card"><summary><span class="narrative-step">${i+1}</span><strong>${esc(r.title)}</strong><span class="narrative-status">${esc(r.status||"")}</span></summary><div class="narrative-content"><p>${esc(r.summary||"")}</p><div class="narrative-fields">${nfield("Forma de conocimiento o práctica",field(r,"Forma de conocimiento o práctica"),true)}${nfield("Materialidad cotidiana",field(r,"Materialidad cotidiana"),true)}${nfield("Función en el Libro I",field(r,"Función recuperada en libro 1"),true)}${nfield("Señal de equilibrio alterado",field(r,"Señal de equilibrio alterado"),true)}${nfield("Relación con la biblioteca",field(r,"Relación con biblioteca"),true)}${nfield("Riesgo de reducción",field(r,"Riesgo de reducción"),true)}${nfield("Vacío prioritario",field(r,"Vacío prioritario"),true)}</div></div></details>`).join("")||'<div class="narrative-empty">No hay civilizaciones registradas.</div>'}</div>`}
const CHARACTERS=[
  {name:"El Custodio",rx:/custodio/i},
  {name:"El contemplativo",rx:/contemplativ/i},
  {name:"El caballero",rx:/caballer/i},
  {name:"La princesa",rx:/princes/i},
  {name:"El jefe mercante y la caravana",rx:/jefe mercante|mercantes?|caravana/i},
  {name:"Los Celum",rx:/celum/i}
];
function matches(r,rx){return rx.test(`${r.title||""} ${r.summary||""} ${JSON.stringify(r.fields||{})} ${r.notes||""}`)}
function recordText(r){return field(r,"Enunciado vigente")||field(r,"Decisión consolidada")||field(r,"Ajustes / precisión")||field(r,"Qué debe resolverse")||r.notes||r.summary||""}
function renderCharacters(data){const dossiers=CHARACTERS.map(c=>({c,canon:data.canon.filter(r=>matches(r,c.rx)),directives:data.decisiones.filter(r=>matches(r,c.rx)),pending:data.pendientes.filter(r=>matches(r,c.rx)),plot:data.libro1.filter(r=>matches(r,c.rx))})).filter(x=>x.canon.length+x.directives.length+x.pending.length+x.plot.length);return`<div class="narrative-head"><div class="eyebrow">Canon · Personajes</div><h2>Personajes y función narrativa</h2><p>El Atlas reúne aquí lo que ya está escrito sobre cada personaje. Cuando faltan rasgos o decisiones, el vacío queda señalado en lugar de completarse por inferencia.</p></div><div class="narrative-list">${dossiers.map((d,i)=>characterCard(d,i)).join("")||'<div class="narrative-empty">No hay caracterización suficiente en los registros actuales.</div>'}</div>`}
function characterCard(d,i){const canon=unique(d.canon.map(recordText)).slice(0,7),directives=unique(d.directives.map(recordText)).slice(0,6),pending=unique(d.pending.map(r=>`${r.title}: ${field(r,"Qué debe resolverse")||r.summary||""}`)).slice(0,6),plot=unique(d.plot.map(r=>`${r.title}: ${field(r,"Consecuencia causal")||r.summary||""}`)).slice(0,8);return`<details class="narrative-card"><summary><span class="narrative-step">${i+1}</span><strong>${esc(d.c.name)}</strong><span class="narrative-status">${canon.length+directives.length} definiciones · ${pending.length} abiertos</span></summary><div class="narrative-content"><div class="character-summary"><span class="pill info">${d.plot.length} tramos del Libro I</span><span class="pill ${pending.length?"open":"good"}">${pending.length?`${pending.length} cuestiones abiertas`:"Sin pendientes detectados"}</span></div>${charSection("Canon y caracterización vigente",canon)}${charSection("Directrices consolidadas",directives)}${charSection("Participación en la trama",plot)}${charSection("Decisiones todavía abiertas",pending)}</div></details>`}
function charSection(title,items){return items.length?`<section class="character-section"><h4>${esc(title)}</h4><ul>${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section>`:""}
const observer=new MutationObserver(schedule);observer.observe(document.getElementById("view"),{childList:true,subtree:true});schedule();
})();
